### ISSUE TITLE
How do i export RSA Private Key to PEM?

### ISSUE THREAD

**Issue by Goutham-Byteridge** [DigitalLeaves/CryptoExportImportManager#6]

**Comment by jmereaux** [comment]
+1

**Comment by flockoffiles** [comment]
+1

**Comment by petershaw** [comment]
That would help a lot.

**Comment by twjazzhuang** [comment]
How do i export EC Private Key ?
I hope it can be import to server or android.

**Comment by DigitalLeaves** [comment]
You should **NEVER** export a private key. If you need to export a private key from a device, something is wrong in the architecture of your system. The private key is supposed to always stay in the device. Only the public one should be disclosed (that's why they are called public and private keys ;)).

**Comment by twjazzhuang** [comment]
Yes, I know this design is very bad.
It is used to change device access data,
Avoid losing data.
In Java above I can output ec private key for base64 encoding,
but this code does not seem to be compatible with iOS.
The server could not decode the ios ec private key,
so I would not be able to restore the user's private key to another device.
So I just want to ask if there is any good idea about the export of EC private key across platforms.

**Comment by DigitalLeaves** [comment]
I would suggest you to change your architecture, generate a master key and sign it symmetrically with a passphrase. Then the user will be able to recover the master key as long as he or she has the passphrase. Exporting private keys is a bad security practice and can bring you headaches on the long run, that's why this class does not support it.

**Comment by twjazzhuang** [comment]
Thank you very much for your suggestion, 
but I don't have the dominion to change this architecture.
Haha.....

**Comment by DigitalLeaves** [comment]
Oh, sorry about that... In that case, I might suggest to talk to the person in charge (CTO? Boss?) and ask him to reconsider the security scenario. Once the private key leaves the device (it doesn't matter how), it's not considered "private" anymore.

If you want to give trust to your customers, that's something to have into account. Also, with the new GDPR regulations, that's not considered a safety practice, so you can run into trouble if you have EU customers/users.
